- deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml
- pkg/apis/cincinnati/v1alpha1/cincinnati_types.go
The Cincinnati API sound a lot like [Cincinnati's graph API][1].  Use "service" instead (which will hopefully not be confused with narrow Kubernetes Services).
[1]: https://github.com/openshift/cincinnati/blob/c1e2b4eb6ae13f093875ae7de45acaa74937c848/docs/design/cincinnati.md#graph-api
> pkg/apis/cincinnati/v1alpha1/cincinnati_types: "API" -> "service"

- pkg/controller/cincinnati/cincinnati_controller.go
- pkg/controller/cincinnati/new.go
fixes #2
This patch includes two related changes:
1. The Pod has two new annotations that contain a checksum of each ConfigMap.
That way when the contents of a ConfigMap change, that will result in a change
to the Pod template, which will in turn cause the Deployment to replace any
current Pods with a new rollout.
2. The creation of kube resource objects is refactored to happen on a single
object. At the beginning of reconciliation, all resources get created once
up-front and are stored in that object for use throughout the reconciliation
workflow. This is especially helpful since resource creation involves rendering
at least one template, which can return an error; handling that case once
up-front makes it possible to then easily reference resources and their
attributes from other code. …
> Ensures Pods get restarted when config changes.

- README.md
- deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml
- deploy/crds/cincinnati.openshift.io_v1alpha1_cincinnati_cr.yaml
- dev/Dockerfile
- docs/graph-data-init-container.md
- pkg/apis/cincinnati/v1alpha1/cincinnati_types.go
- pkg/controller/cincinnati/cincinnati_controller.go
- pkg/controller/cincinnati/names.go
- pkg/controller/cincinnati/new.go
Adds a graphDataImage property to the CRD.
The init container is created when the property is set. If unset
Cincinnati is configured to fetch the graph data from the specified
github repository.
If both graphDataImage and gitHub repository properties are set,
graphDataImage will take precedent.
> Option to load graph data from an init container

- Makefile
- OWNERS
Makefile contains a unit-test target used by OpenShift CI.
> Add Makefile and OWNERS

- deploy/crds/cincinnati.openshift.io_v1alpha1_cincinnati_cr.yaml
- deploy/olm-catalog/cincinnati-operator/0.0.1/cincinnati-operator.v0.0.1.clusterserviceversion.yaml
- docs/external-registry-ca.md
- pkg/apis/cincinnati/v1alpha1/cincinnati_types.go
- pkg/controller/cincinnati/cincinnati_controller.go
- pkg/controller/cincinnati/cincinnati_controller_test.go
- pkg/controller/cincinnati/names.go
- pkg/controller/cincinnati/new.go
Remove the CertConfigMapKey field and instead look for a hardcoded key,
'cincinnati-registry', in the openshift-config ConfigMap.  Having a
hardcoded value won't affect usability and it allows us to safely locate
the CA Cert.
The patch is a good segue into the future where we can potentially bundle
all the certs found in the openshift-config ConfigMap and mount them into
Cincinnati.
> Simplify the Cincinnati Operator API

- hack/functest.sh
Fix go get: disabled by -mod=vendor
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8863/rehearse-8863-pull-ci-openshift-cincinnati-operator-release-4.5-cincinnati-operator-e2e-aws/2
> export GOFLAGS

- pkg/controller/cincinnati/cincinnati_controller.go
- pkg/controller/cincinnati/cincinnati_controller_test.go
- pkg/controller/cincinnati/new.go
Add a new function that appends the CA volume and volumemount to the
deployment and graph builder container respectively.
> refactor: new function to handle adding external CA

- pkg/controller/cincinnati/cincinnati_controller.go
The route is configured with a default cert from the ingress. If the customer wants to use a different TLS cert/key pair,this patch allows them to manually modify the route object with their cert/key and the controller won't override the change. If the CR or the route is deleted, the customer would have to remember to make that change again.
Alternatively, we could change our API to ask for certificate, private key and CA certificate. Other option is to ask the customer to create a new route themselves with the certificate they want.
> Allow user to change the cert on the route outside of the CR

- pkg/apis/cincinnati/v1beta1/cincinnati_types.go
- pkg/controller/cincinnati/new.go
As of today, the operator will always use "0.0.0.0" as the binding address for the different services. When running on IPv6 environments that cause the services to fail since there are not IPv4 addresses available in the pod. With this change, the user will be able to choose which address is used when binding. 
By default, if no value is provided for the `address` property in the spec, we will configure "0.0.0.0", otherwise, we will configure the address configured by the user. 
Let me know what you think about the implementation, if it looks good to you I'll update the docs accordingly.
> Added support for choosing bind address

- pkg/controller/cincinnati/cincinnati_controller.go
- pkg/controller/cincinnati/cincinnati_controller_test.go
- pkg/controller/cincinnati/names.go
- pkg/controller/cincinnati/new.go
The [basic auth support](https://github.com/openshift/cincinnati/pull/292) patch in Cincinnati added a `credentials_path` to point to a docker config file with basic auth for registries.  Since it's likely the installer is using the same local registry as CIncinnati, we'll mount the `pull-secret` secret into the graph builder.  This avoids the user having to essentially create the pull-secret twice.
> Copy pull-secret into graphbuilder

- deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml
- pkg/apis/cincinnati/v1beta1/cincinnati_types.go
Users must point the update service at a repository so the graph builder can scrape for primary release metadata.
Also require the `spec`, but leave `status` optional.  This allows users to upload a manifest, while leaving the status empty for the controller to fill in later.
WIP because I need to figure out how to regenerate the machine-written portions of this package.
> pkg/apis/cincinnati/v1beta1: Explicitly require registry and repository

- pkg/controller/cincinnati/mapper_test.go
- pkg/controller/cincinnati/new.go
Generated with:
```console
$ gofmt -s -w $(find pkg -type d)
```
> pkg/controller/cincinnati: Remove redundant slice entry types

- OWNERS
@LalatenduMohanty  @wking @steveeJ @jottofar @vrutkovs
> Add OTA team as OWNERS

- docs/disconnected-cincinnati-operator.md
- docs/graph-data-init-container.md
- pkg/controller/cincinnati/new.go
Builds on #63; you may want to review that first.
We had used `InsecureEdgeTerminationPolicyAllow` since the route landed in 1fdf865825 (#30).  The motivation for that value didn't make it into the Git commit message, but from [discussion in the GitHub pull request][1], it was:
* `InsecureEdgeTerminationPolicyAllow` is the default termination policy.
* [Cincinnati's docs][2] have no preference.
However, we really, really want HTTPS security for cluster-version operators making upstream requests for update recommendations.  There are long-term plans for tightening down guards against malicious, compromised, or man-in-the-middled update recommendation services, but today we have yet to land even guards as basic as "[upstream is lying about the version string associated with a given release …
> pkg/controller/cincinnati: Use InsecureEdgeTerminationPolicyNone

- docs/disconnected-cincinnati-operator.md
- docs/graph-data-init-container.md
Or in the `oc -n ... create ...` call that pushes them into the cluster.  And also use the `NAMESPACE` variable when looking up the policy engine's route.
We could add an environment variable for the Cincinnati manifest's name, but I think `example-name`, which I'm pivoting to, is clear enough in pattern-matching that we don't need a formal environment variable.
> docs: Set namespace for Cincinnati manifests

- README.md
So new folks understand where the `operator-sdk` command should come from, or remember to look in `vendor/` to see which version to use:
```console
$ grep '#.*operator-sdk' vendor/modules.txt 
```
> README: Document operator-sdk installation

- Dockerfile
- build/Dockerfile
No need to shift this down into a subdirectory.  Add a symlink to give existing consumers some time to migrate.
> Dockerfile: Shift to the repo root

- functests/cincinnati_creation_test.go
Pulled out of #65, since this should green up CI and seems orthogonal to the SDK pivot.
> functests: Add set up method to add schemes

- Makefile
- hack/functest.sh
And drop the one-line functest.sh wrapper.  Also add a `-v` so we get the `t.Log` output to help debug failures.
> Makefile: Inline the functest invocation

- OWNERS
Based on @sdodson's [comment][1]:
> It's used downstream to facilitate mapping to BZ Components.
I'm not sure if this property matters to us, because we are a separate Red Hat product, not a component under the OpenShift Container Project product.  But `Cincinnati Operator` no longer exists anywhere, so pointing folks at our current product name isn't breaking it any worse.
[1]: https://github.com/openshift/cluster-version-operator/pull/344#issuecomment-610902992
> OWNERS: Bugzilla product should be "OpenShift Update Service"

- Dockerfile
The outgoing docker.io image was [subject to docker.io rate limiting][1]:
```
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: while pulling "docker://docker.io/openshift/origin-release:golang-1.13" as "docker.io/openshift/origin-release:golang-1.13"...
```
The new image matches openshift/cluster-version-operator@7cb2662924 (openshift/cluster-version-operator#468).  Matching builders with the CVO reduces our exposure by consolidating around a smaller set of Go builder images.
[1]: https://github.com/openshift/cincinnati-operator/pull/82#issuecomment-728254564
> Dockerfile: Bump builder to ART's Go 1.15 image

- Dockerfile
- Makefile
- PROJECT
- README.md
- config/manager/manager.yaml
- hack/deploy.sh
> Changing the updateservice name to update-service

- OWNERS
The ACM devs kindly scaffolded this operator, but have since handed it off to the updates folks.  This commit completes the ownership transition begun in f7860a3b9b (#62).
I've also applied a case-insensitve sort to the remaining entries.
> OWNERS: Drop Advanced Cluster Management folks

- Dockerfile
- Makefile
- main.go
- version/version.go
We've been tracking a nominal operator version since 52a976598c, but this is one more thing we'd need to remember to bump between releases, and it's hard to know what version number we'd want to use before we are building a release.  Drop it from the operator to give us one less moving piece.
I'd be fine including the Git commit hash in some early logging, and injecting that hash at build time, but I've punted on that for now.  The operator images should include that information in the image metadata anyway.
The OLM bundles will remain versioned, but bundle version can be a decision made at bundle-build time, pulling in whichever operator image they want to pull in.
> *: Use Git description for version information

- Makefile
- config/manifests/bases/update-service-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/scorecard/bases/config.yaml
- config/scorecard/kustomization.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
Modifies Makefile and creates the config/manifests artifacts which support bundling and is generated by the new recipe 'gen-for-bundle'.
In its current form this PR assumes that the official build will run the `bundle` target and therefore only needs the `config/manifests` directory. Another possibility is that the official build only builds the bundle image in which case we would run and check-in the results of the `bundle` recipe. The official build would then use these artifacts to build the bundle image which is then used to create or update a bundle index.
The additional recipes added to the Makefile are described in detail below.
`manifests` generates manifests, e.g. CRD, RBAC etc., and is run by development when required.
`gen-for-bundle` generates kustomize bases and a …
> Operator bundle: changes to support operator bundling

- docs/disconnected-cincinnati-operator.md
In case the user creates the Cincinnati CR with a longer name, there
might be a case where the route's hostname exceeds 63 chars. This will
result in the route not getting created, inturn crashing the operator.
Document using a shorter name for Cincinnati CR to prevent this
issue.
> document using shorter name for Update Service CR

- config/samples/updateservice.operator_v1_updateservice.yaml
To prevent invalid host error upon route creation. Also replaced incorrect generated spec contents with defaulted "replicas" value.
> Bug 1939788: config/samples: Shorten name

- README.md
- config/manager/manager.yaml
- config/olm-catalog/updateservice-operator/1.0.0/updateservice-operator.v1.0.0.clusterserviceversion.yaml
- hack/deploy.sh
- main.go
Changing the name to make OSBS auto repo/registry replacements to work.
Auto digest_pinning, repo_replacements, registry_replacements necessary for releasing the image to different repository (stage, prod) etc. 
Refer
https://osbs.readthedocs.io/en/latest/users.html#pullspec-locations for
details
Also changed OPERATOR_IMAGE to RELATED_IMAGE_OPERATOR for consistency
> Bug 1945026: Changing the name to make OSBS auto repo/registry replacements to work

- hack/deploy.sh
As registry.svc.ci is deprecated now
> Changing to registry.ci in deploy.sh

- Makefile
Else go test was giving success everytime even if the test cluster was
deleted as the result was cached
$ go test -v ./functests/...
=== RUN   TestCustomResource
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
--- PASS: TestCustomResource (241.87s)
PASS
ok  	github.com/openshift/cincinnati-operator/functests	(cached)
> Expire all test results in the go build cache before new run

- Makefile
The CI kept failing in release-4.6 branch and the root cause is the
sracpping time graph-builder container in OSUS operand which is around
8 minutes or so. However this adds the
total test duration more than 10 mins which causing the test to fail.
> Increasing the go test timeout to 20 minutes.

- controllers/updateservice_controller.go
Before this commit:
```console
$ oc -n openshift-update-service get -o yaml updateservice sample
...
status:
conditions:
- lastHeartbeatTime: "2021-07-21T16:29:15Z"
lastTransitionTime: "2021-07-21T16:29:15Z"
message: 'image.config.openshift.io.Spec.AdditionalTrustedCA.Name not found for
image (Name: cluster, Namespace: )'
reason: FindAdditionalTrustedCAFailed
status: "False"
type: RegistryCACertFound
...
```
Which is a bit alarming for the "no registry CAs injected; you're fine".  This commit will pivot to a `NotConfigured` reason and a clearer message:
image.config.openshift.io.Spec.AdditionalTrustedCA.Name not set for image name cluster
I'm also dropping the rendered namespace, because [the Image config is cluster-namespaced][1].
[1]: …
> controllers/updateservice_controller: Use NotConfigured for "no CAs configured"

- config/manifests/bases/update-service-operator.clusterserviceversion.yaml
After moving to v1.9.0 3 three scorecard tests were failing. The full output of the failed scorecard tests is below. 
The first "olm-status-descriptors" was addressed by adding `statusDescriptors`, the second "olm-crds-have-resources" by adding `resources`, and the third "olm-spec-descriptors" by adding `specDescriptors`.  These are described [here](https://sdk.operatorframework.io/docs/olm-integration/generation/#csv-fields).
`{
"kind": "Test",
"apiVersion": "scorecard.operatorframework.io/v1alpha3",
"spec": {
"image": "quay.io/operator-framework/scorecard-test:v1.9.0",
"entrypoint": [
"scorecard-test",
"olm-status-descriptors"
],
"labels": {
"suite": "olm",
"test": "olm-status-descriptors-test"
}
},
"status": {
"results": [
{
"name": "olm-status-descriptors",
"log": "Loaded …
> Modify CRD so passes all scorecard tests

- config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
Set `additionalPrinterColumns` for UpdateService CRD to provide more information to a user about the UpdateService resource.
Previously running the `oc get -o wide ...` command only displayed the name and the age of the specific running UpdateService resources.
Display the `policyEngineURI`, `releases`, `graphDataImage`, and the `ReconcileCompleted` condition status to provide more information to a user about the UpdateService resource. Set the priority of these `additionalPrinterColumns` accordingly to list them only when the `-o wide` flag is provided.
Pull request is related to https://issues.redhat.com/browse/OTA-449
> Set additionalPrinterColumns for UpdateService CRD

- functests/updateservice_creation_test.go
This would make gather-* steps collect the state of deployment in prow job artifacts when operator-e2e fails
> test: delete CR on successful pass only

- controllers/new.go
This allows us to use keep-alived connection to check that policy-engine is still running. This becomes important under load, when a new liveness probe connection becomes expensive.
> Use http probe for policy-engine

- hack/deploy.sh
Removed openshift CI case as its no longer being used (image pullspecs are passed as RELATED_IMAGE_OPERATOR/RELATED_IMAGE_OPERAND/GRAPH_DATA_IMAGE env vars)
> deploy.sh: show image pull specs when deploying

- controllers/updateservice_controller.go
such as graphDataImage updates.
> Bug 1939855: controllers/updateservice_controller.go: handle init container changes

- controllers/new.go
- controllers/updateservice_controller.go
- controllers/updateservice_controller_test.go
As policy/v1beta1 API version of PodDisruptionBudget is no longer served as of OCP 4.12 i.e. kubernetes v1.25
> Migrate policy/v1beta1 PodDisruptionBudget to policy/v1

- controllers/new.go
add the liveness and readiness probes added to
cincinnati operand since https://github.com/openshift/cincinnati/pull/740
> add liveness and readiness probe for PE 

- dev/Dockerfile
Since tar is run as root, it will attempt to preserve the user/group of the files in the archive by default, which leads to these errors when unpacking the graph data archive:
tar: version: Cannot change ownership to uid 1000950000, gid 0: Invalid argument
Passing the --no-same-owner flag to tar will expand the archive contents as root:root instead of trying to preserve the non-existent uid from the original archive.
> init Dockerfile: Fix tar error setting user

- functests/updateservice_creation_test.go
This makes the tests work against OCP 4.12+ clusters. The failure can be seen e.g. in [this rehearsal](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39394/rehearse-39394-pull-ci-openshift-cincinnati-operator-master-operator-e2e-latest-osus-412/1658587442212507648).
> functests: stop using v1beta1 PDB API

- bundle.Dockerfile
- bundle/manifests/leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
- bundle/manifests/leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
- bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- bundle/manifests/updateservice-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- bundle/manifests/updateservice-operator-metrics_v1_service.yaml
- bundle/manifests/updateservice-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml
- bundle/manifests/updateservice.operator.openshift.io_updateservices.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/manager/kustomization.yaml
Just ran an existing `Makefile` target /shrug:
```console
cd config/manager && /usr/bin/kustomize edit set image controller=controller:latest
/usr/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 5.0.2-dev --channels=v1 --default-channel=v1
INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Creating bundle/metadata/annotations.yaml    
INFO[0000] Bundle metadata generated successfully       
operator-sdk bundle validate ./bundle
INFO[0000] All validation tests have completed successfully
```
The bundle will not work by itself: we are not publishing the operator images anywhere (except the productized images ofc) and we are not publishing cincinnati images anywhere suitable either …
> Include bundle manifests and Dockerfile

- controllers/names.go
- controllers/new.go
- docs/external-registry-ca.md
add additionalTrustedCA as well as ClusterTrustedCA to SSL_CERT_DIR this is required when the user has both CAs set.
earlier we used to ignore additionalTrustedCA when CLusterCA was present
see: https://www.openssl.org/docs/man1.0.2/man1/c_rehash.html
> OCPBUGS-16898 : Add both trusted and additional CA to SSL_CERT_DIR

- controllers/names.go
- controllers/new.go
- docs/external-registry-ca.md
Reverts openshift/cincinnati-operator#172
We will fix the bug with another approach.
For now, we'll prefer cluster-wide-proxy over additionalTrustedCAs
> Revert "OCPBUGS-16898 : Add both trusted and additional CA to SSL_CERT_DIR"

- Makefile
- api/v1/updateservice_types.go
- config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
- config/rbac/role.yaml
- controllers/names.go
- controllers/new.go
- controllers/updateservice_controller.go
- dev/Dockerfile
- functests/updateservice_creation_test.go
Catching up with openshift/cincinnati@efe98dcbbbc6 (openshift/cincinnati#816), allowing users to retrieve signatures from the metadata Route.  For signatures provided via the graph-data image, this will provide a more convenient access than pushing signature ConfigMaps to individual clusters.  openshift/enhancements#1485 is in flight with a proposed mechanism to configure clusters to consume this signature-metadata endpoint.
> OTA-1014: controllers: Add metadata container and Route

- bundle/manifests/updateservice.operator.openshift.io_updateservices.yaml
Generated with:
```console
$ cp config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml bundle/manifests/updateservice.operator.openshift.io_updateservices.yaml
```
to catch up with 6b266d2707 (#173) suggests I could have done this with `make bundle VERSION=5.0.3-dev` or some such, but I don't have `operator-sdk` installed at the moment.
> OTA-1014: bundle/manifests: Update UpdateService CRD to pick up metadataURI

- controllers/updateservice_controller.go
Avoiding [`encountered unexpected container in pod` issues][1]:
```console
$ oc -n install-osus-here logs updateservice-operator-5bdfcff5c5-wqjdt|grep metadata|tail -n2
1.701074599173428e+09    INFO    controller_updateservice    Updating Service    {"Request.Namespace": "install-osus-here", "Request.Name": "sample", "Namespace": "install-osus-here", "Name": "sample-metadata"}
1.7010745992028923e+09    INFO    controller_updateservice    encountered unexpected container in pod    {"Request.Namespace": "install-osus-here", "Request.Name": "sample", "Container.Name": "metadata"}
```
which is also [seen][2] in [this CI run][3].
[1]: https://issues.redhat.com/browse/OTA-958?focusedId=23535225&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23535225
[2]: …
> OTA-1014: controllers/updateservice_controller: Handle metadata container in ensureDeployment

- controllers/new.go
this commit removes the SSL_CERT_FILE env variable as
we're programmatically adding SSL certs to requests
in cincinnati and no longer need this env variable
for CA certs to work.
> Remove unnecessary env variables

- api/v1/updateservice_types.go
- bundle/manifests/updateservice.operator.openshift.io_updateservices.yaml
- config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
The Go-side 'optional' was not enough to get these optional, so talk to kubebuilder directly.  We need metadataURI to be optional to [avoid][1]:
```console
$ oc -n openshift-update-service get -o json installplan install-wpgw2 | jq '.status.conditions[]'
{
"lastTransitionTime": "2024-05-20T07:05:46Z",
"lastUpdateTime": "2024-05-20T07:05:46Z",
"message": "error validating existing CRs against new CRD's schema for \"updateservices.updateservice.operator.openshift.io\": error validating updateservice.operator.openshift.io/v1, Kind=UpdateService \"openshift-update-service/sample\": updated validation is too restrictive: [].status.metadataURI: Required value",
"reason": "InstallComponentFailed",
"status": "False",
"type": "Installed"
}
```
We need those existing 5.0.2 UpdateService to be …
> OCPBUGS-33939: api/v1/updateservice_types: Explicit +kubebuilder:validation:Optional

- Makefile
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- bundle/manifests/updateservice.operator.openshift.io_updateservices.yaml
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.5.4
vs
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.4.2
The latest version (currently `v5.4.2`) supports more platforms.
Generated by:
```console
$ operator-sdk version
operator-sdk version: "v1.28.0-ocp", commit: "9faa5105bfa6ca52490a17dbaee0653dedd0e536", kubernetes version: "v1.26.0", go version: "go1.19.6", GOOS: "darwin", GOARCH: "arm64"
$ kustomize version
v5.4.2
```
> Bump kustomize version to 5.4.2

- config/default/kustomization.yaml
- config/manifests/kustomization.yaml
```console
cd config/manager && /Users/hongkliu/go/bin/kustomize edit set image controller=controller:latest
/Users/hongkliu/go/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 5.0.2-dev --channels=v1 --default-channel=v1
INFO[0000] Creating bundle/metadata/annotations.yaml    
INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Bundle metadata generated successfully       
operator-sdk bundle validate ./bundle
INFO[0000] All validation tests have completed successfully 
```
This PR fixes the first warning "Warning: 'bases' is deprecated" from `kustomize`.
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/bases/
The 2nd one about "patchesJson6902" is a bit involved. It is a much …
> Fix a kustomize warning: 'bases' is deprecated

- bundle.Dockerfile
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
```console
$ podman run --platform=linux/amd64 --rm -it --entrypoint='["bash"]' registry.ci.openshift.org/origin/4.15:operator-sdk
bash-4.4$ operator-sdk version
operator-sdk version: "v1.31.0-ocp", commit: "08d08dd8e4da74c83fffa812fb8eb382eb0a072d", kubernetes version: "v1.26.0", go version: "go1.20.12 X:strictfipsruntime", GOOS: "linux", GOARCH: "amd64"
```
The [CI env.](https://github.com/openshift/release/blob/d6d69e0bf41d63f4e6848ac492498406116b4c31/ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-master.yaml#L6-L9) has been moved forward and we might want to keep the version aligned with it. The manifests in bundles are [used only in CI or by QE](https://github.com/openshift/cincinnati-operator/pull/173) and thus should be safe enough to do.
The real …
> cincinnati-operator: bump operator-sdk versions to v1.31.0-ocp

- Makefile
- api/v1/updateservice_types.go
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
Generated by:
```console
$ make manifests
```
with
```
$ controller-gen --version
Version: v0.13.0
$ operator-sdk version    
operator-sdk version: "v1.31.0-ocp", commit: "23376a866e765de8e097859b0b917cdb75fdc2b0", kubernetes version: "v1.26.0", go version: "go1.20.12", GOOS: "darwin", GOARCH: "arm64"
$ go version
go version go1.21.1 darwin/arm64
```
- Removed `CRD_OPTIONS` which does not work with `controller-gen` of `v0.13.0`. The version has been used already since https://github.com/openshift/cincinnati-operator/commit/6b266d27077096317338733693da0768a31e9b3e of https://github.com/openshift/cincinnati-operator/pull/176 There the `controller-gen` cmd has the `crd` as an arg already.
- Added  markers like `+kubebuilder:printcolumn` to let `controller-gen` …
> Fix manifests of Makefile

- api/v1/updateservice_types.go
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- config/manifests/bases/update-service-operator.clusterserviceversion.yaml
This PR is generated by
```console
$ ./bin/operator-sdk version                        
operator-sdk version: "v1.31.0-ocp", commit: "23376a866e765de8e097859b0b917cdb75fdc2b0", kubernetes version: "v1.26.0", go version: "go1.20.12", GOOS: "darwin", GOARCH: "arm64"
$ operator-sdk generate kustomize manifests -q
```
It turns out that `config/manifests/bases/update-service-operator.clusterserviceversion.yaml` is also generated (by `operator-sdk generate kustomize manifests -q`).
It copies the `kubernetes.io/description` annotation over from the `config/manager/manager.yaml` that is exactly we did manually.
> Rerun operator-sdk generate kustomize manifests

- Makefile
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- Download the tools such as `kustomize` and `operator-sdk` on the fly, like [the operator sdk's example](https://github.com/operator-framework/operator-sdk/blob/e95abdbd5ccb7ca0fd586e0c6f578e491b0a025b/testdata/go/v4/memcached-operator/Makefile#L220). We will use them in CI.
- The existing target `bundle` is aligned with [the operator sdk's example](https://github.com/operator-framework/operator-sdk/blob/e95abdbd5ccb7ca0fd586e0c6f578e491b0a025b/testdata/go/v4/memcached-operator/Makefile#L257).
- The new target `pull-ci-openshift-cincinnati-operator-master-verify-generate` will be used by the job from https://github.com/openshift/release/pull/54417
> Add verify-generate in Makefile

- Makefile
- functests/utils.go
It took over 10m in the last successful run: `12m`
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cincinnati-operator/227/pull-ci-openshift-cincinnati-operator-master-operator-e2e-new-ocp-published-graph-data/1912692491069427712/artifacts/operator-e2e-new-ocp-published-graph-data/e2e-test/build-log.txt | rg 'Dep.*ava|example created'
I0417 02:30:19.606998    9932 utils.go:113] Deployment updateservice-operator available (1/1)
I0417 02:30:21.224743    9932 utils.go:86] updateservice.updateservice.operator.openshift.io/example created
I0417 02:42:21.266104    9932 utils.go:113] Deployment example available (1/1)
```
This one is taken from [the job for this RP](https://prow.ci.openshift.org/view/gs/test-platform-result …
> functests: increase 10m to wait for deployment to be ready

- Dockerfile
UBI9 has a wider range of FIPS-support of OpenShift and Host Operating System than UBI8 [1].
[1]. https://docs.google.com/document/d/1CTpSwITQfOgoOTlPITZNJZy0ltYz60hxkmWsLemCqw0/edit?usp=sharing
> OTA-1491: Bump base image to ubi9

- config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml
The file `config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml`
is used only in func-test.
```console
$ rg v1_updateservice_cr
functests/utils.go
81:     cmd := exec.CommandContext(ctx, "oc", "apply", "-f", "../config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml", "-n", operatorNamespace)
hack/kustomize_edit_env_vars.sh
31:${SED_CMD} -i "s|your-registry/your-repo/your-init-container|$GRAPH_DATA_IMAGE|" config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml
```
`kustomize_edit_env_vars` above is used as a prep for e2e.
The `releases` in the updateservice's sepc is changed to "quay.io/redhat/openshift-cincinnati-test-public-manual" ([having 2 tags](https://quay.io/repository/redhat/openshift-cincinnati-test-public-manual?tab …
> OTA-1517: Scrape a smaller release repo in func-e2e

- api/v1/updateservice_types.go
- bundle/manifests/update-service-operator.clusterserviceversion.yaml
- bundle/manifests/updateservice.operator.openshift.io_updateservices.yaml
- config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
- config/manifests/bases/update-service-operator.clusterserviceversion.yaml
- controllers/names.go
- controllers/new.go
- controllers/updateservice_controller.go
- dev/Dockerfile
- functests/updateservice_creation_test.go
Follow up [the Slack discussion](https://redhat-internal.slack.com/archives/CJ1J9C3V4/p1746204277175029?thread_ts=1746200201.982019&cid=CJ1J9C3V4).
Remove metadata-helper from the cincinnati-operator.
Practically, the last 3 commits from https://github.com/openshift/cincinnati-operator/pull/176/commits are reverted by this PR.
Is it OK if we just remove an existing API like [UpdateService.status.MetadataURI](https://github.com/openshift/cincinnati-operator/compare/master...hongkailiu:cincinnati-operator:rm-metadata-helper?expand=1#diff-9a932dc9a2e3a1f3c1dda661968d210b80b06436b01883233b3035c75c2562d4L57)?
I am not sure if any user will use that field in their automation which may collapse if the field disappears?
The bright part is that the field is in status which means it should be …
> Remove metadata-helper
