deploy/olm-catalog/cincinnati-operator/0.0.1/cincinnati-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/cincinnati-operator/cincinnati-operator.package.yaml, deploy/operator.yaml
- Start using images from https://quay.io/organization/cincinnati
- First pass at a CSV file
=> Create operator CSV file

go.sum, pkg/controller/cincinnati/cincinnati_controller.go, pkg/controller/cincinnati/mapper.go, pkg/controller/cincinnati/mapper_test.go
=> Add watches on Image and ConfigMap

README.md, deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml, deploy/crds/cincinnati.openshift.io_v1alpha1_cincinnati_cr.yaml, deploy/olm-catalog/cincinnati-operator/0.0.1/cincinnati-operator.v0.0.1.clusterserviceversion.yaml, deploy/role_binding.yaml, docs/graph-data-init-container.md, pkg/apis/cincinnati/v1alpha1/cincinnati_types.go, pkg/controller/cincinnati/cincinnati_controller.go, pkg/controller/cincinnati/cincinnati_controller_test.go, pkg/controller/cincinnati/new.go
=> Remove git fields from CRD

Makefile, functests/common.go, functests/functests_suite_test.go, functests/service_account_creation_test.go, go.mod, go.sum, hack/functest.sh
This is currently a basic functional test to create a service account. I want to verify how it runs through the CI. More tests will be added later.
To test locally,
create a cluster and set the KUBECONFIG env var whose value is the file path of the kubeconfig for your cluster. Then run `make func-test`
=> Functional test cases for cincinnati operator

deploy/olm-catalog/cincinnati-operator/0.0.1/cincinnati-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/cincinnati-operator/0.0.1/cincinnati.openshift.io_cincinnatis_crd.yaml, deploy/olm-catalog/cincinnati-operator/cincinnati-operator.package.yaml
- Add missing metadata field `displayName`
- Copy the CRD down next to the CSV
- Remove an extra `,` in alm-examples
=> Modify some bundle metadata

pkg/apis/cincinnati/v1beta1/cincinnati_types.go, pkg/controller/cincinnati/cincinnati_controller.go, pkg/controller/cincinnati/cincinnati_controller_test.go
=> Adding status condition to track the status of cincinnati registry cert

pkg/controller/cincinnati/cincinnati_controller.go, pkg/controller/cincinnati/cincinnati_controller_test.go, pkg/controller/cincinnati/names.go, pkg/controller/cincinnati/new.go
backport b7b5b01dc553473e2400b40cd0d41f043e5079f7
=> cherrypick b7b5b01dc553473e2400b40cd0d41f043e5079f7

Dockerfile
registry.svc.ci is deprecated
replace the image with registry.ci image
=> use registry.ci image in dockerfile

OWNERS
Stefan has moved on to other things :(.
=> OWNERS_ALIASES: Drop steveeJ

README.md
=> Adding documentation links to the readme

docs/disconnected-cincinnati-operator.md, docs/graph-data-init-container.md
=> Updating the docs as some parts not required any more

README.md
Catching up with 9a20fde8e9 (#125).
=> README: Bump documented operator SDK to 1.9

README.md
=> Docs: Adding steps to generate bundle manifests

controllers/names.go, controllers/new.go, controllers/updateservice_controller.go
before creating the new route old as we have changed the route syntax in 8cea4f33836e0aeaf8de9cd8b1f37f569545f43f
=> Bug 2101732: Checking if an route exists with old syntax

controllers/names.go, controllers/new.go, controllers/updateservice_controller.go, controllers/updateservice_controller_test.go
Create a trusted-ca config map when using cluster-wide-proxy this will mount the cluster-wide CA to cincinnati containers
=> add support for cluster-wide certs

Dockerfile
Missed this in PR https://github.com/openshift/cincinnati-operator/pull/155
=> Update dockerfile for go118

OWNERS
Jack isn't on the team any more.
Fixing the component for CVE routing.
=> Minor OWNERS file updates

dev/Dockerfile, docs/disconnected-updateservice-operator.md
use the new /graph-data endpoint on upstream update service to download the tarball for creating graph data container
=> [dist] update the dockerfile to use new osus endpoint

OWNERS
@vrutkovs is focusing on assisted-installer stuff now.
=> OWNERS: Prune vrutkovs

.gitignore
Follow up https://redhat-internal.slack.com/archives/CJ1J9C3V4/p1719503709965829?thread_ts=1719503212.427149&cid=CJ1J9C3V4
According to https://git-scm.com/docs/gitignore#_description , I should have set up the git-ignore for IDE folders on my laptop (instead of the target git repo here) as it may not be shared by other developers.
=> Remove IDE folders in .gitignore

api/v1/updateservice_types.go, controllers/names.go, controllers/new.go, controllers/updateservice_controller.go, dev/Dockerfile, functests/updateservice_creation_test.go
revert metadata helper container and its routes as we don't plan on serving release images anymore
=> revert metadata helper container and route

Makefile, config/manager/manager.yaml, hack/kustomize_edit_env_vars.sh
To keep up with the example in operator-sdk:
- Add a namespace like [the example](https://github.com/operator-framework/operator-sdk/blob/e95abdbd5ccb7ca0fd586e0c6f578e491b0a025b/testdata/go/v4/memcached-operator/config/manager/manager.yaml#L2).
- Modify `deploy` like [the example](https://github.com/operator-framework/operator-sdk/blob/e95abdbd5ccb7ca0fd586e0c6f578e491b0a025b/testdata/go/v4/memcached-operator/Makefile#L194).
=> Update deploy in Makefile

Makefile
It is going to simplify [the commands in the presubmit](https://github.com/openshift/release/blob/e4b98d1804ed4cd88854a5977065209f9d1ebc83/ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-master.yaml#L100).
=> Add a new Make target scorecard-test

Makefile, README.md, config/default/kustomization.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/role_binding.yaml, functests/utils.go, tools/create-osus.sh, tools/create-sub-group.sh
Follow up https://github.com/openshift/cincinnati-operator/pull/199#discussion_r1683118686
The PR is generated by:
```console
$ rg openshift-updateservice -l | while read file; do gsed -i 's/openshift-updateservice/openshift-update-service/g' $file; done
```
=> Replace openshift-updateservice with openshift-update-service

config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml
Follow up https://github.com/openshift/cincinnati/pull/1019
=> Use quay.io/openshift-ota/openshift-cincinnati-test-public-manual for e2e
